export type Lang = "fr" | "en";

export const FL = {
  fr: {
    accueil: "← Accueil",
    retourMissions: "← Missions",
    voirMissions: "Missions →",
    voirAnalyser: "Analyser →",
    voirFragments: "Fragments →",
    annuler: "Annuler",
    enregistrer: "Enregistrer",
    supprimer: "Supprimer",
    ouvrir: "Ouvrir →",
    modifier: "Modifier",
    modifierPanel: "Modifier ▼",
    fermerPanel: "Fermer ▲",
    freelanceSubtitle: "Analyser des demandes · Gérer des missions",
    analyserDemande: "Analyser une demande",
    collerMessage: "Coller le message brut du client",
    messageClient: "Message client",
    placeholderMessage: "Coller ici le message brut du client, le brief, ou la demande reçue par email…",
    analyserBtn: "Analyser la demande →",
    configurerTarifs: "Configurer les tarifs",
    typesProjet: "Types de projet",
    ajouterType: "+ Ajouter un type",
    coefficients: "Coefficients",
    autres: "Autres",
    versionSuppl: "Version supplémentaire ($)",
    acompteConfig: "Acompte (ex : 0.50 = 50 %)",
    reinitialiser: "Réinitialiser",
    analyseInitiale: "Analyse initiale",
    modificationsEnCours: "● Modifications en cours",
    analyseValideeFeedback: "✓ Analyse validée",
    aucuneModification: "Aucune modification",
    prixTotal: "Prix total",
    tempsEstime: "Temps estimé",
    typeBtn: "Type ↗",
    acompteLabel: "Acompte",
    creerMission: "Créer la mission →",
    validerAnalyse: "Valider l'analyse",
    analyseValideeBtn: "Analyse validée ✓",
    aConfirmer: "À confirmer avec le client",
    infoSingulier: "info à confirmer",
    infoPluriel: "infos à confirmer",
    informationsDetectees: "Informations détectées",
    informationsDeduites: "Informations déduites",
    checklist: "Checklist de travail",
    client: "Client",
    typeDeProjet: "Type de projet",
    deadline: "Deadline",
    urgence: "Urgence",
    longueur: "Longueur",
    versions: "Versions",
    elementsClient: "Éléments fournis",
    complexite: "Complexité",
    mode: "Mode",
    objectif: "Objectif",
    style: "Style",
    canal: "Canal",
    haute: "Haute ↑",
    normale: "Normale",
    basse: "Basse",
    court: "Court (< 300 mots)",
    moyen: "Moyen (300–800 mots)",
    long: "Long (800–1500 mots)",
    tresLong: "Très long (> 1500 mots)",
    simple: "Simple",
    standard: "Standard",
    complexe: "Complexe",
    details: "Détails ▼",
    reduire: "Réduire ▲",
    longueurSection: "Longueur",
    complexiteSection: "Complexité",
    urgenceSection: "Urgence",
    missions: "Missions client",
    nouvelleMission: "+ Nouvelle mission",
    aucuneMission: "Aucune mission pour l'instant.",
    nom: "Nom",
    briefClient: "Brief client",
    modeEcriture: "Mode d'écriture",
    creerMissionBtn: "Créer la mission",
    briefFourni: "Brief fourni",
    textesAProduire: "Textes à produire",
    aucunTexte: "Aucun texte dans cette mission.",
    ajouterTexte: "+ Ajouter un texte",
    textesSectionLabel: "Textes",
    nouveauTexte: "Nouveau texte",
    titreField: "Titre",
    typeField: "Type",
    texteField: "Texte *",
    ajouter: "Ajouter",
    brutClient: "Brut client",
    enTravail: "En travail",
    copierIA: "Copier pour IA",
    genererPrompt: "Générer prompt →",
    copie: "✓ Copié",
    missionIntrouvable: "Mission introuvable.",
    statutAFaire: "à faire",
    statutEnCours: "en cours",
    statutTermine: "terminé",
    placeholderClient: "Nom du client",
    placeholderDeadline: "Ex : 15/05, vendredi, sous 3 jours",
    placeholderObjectif: "Objectif principal du projet",
    placeholderStyle: "Ex : sobre / élégant, dynamique / percutant",
    placeholderTitre: "Ex : Page d'accueil (optionnel)",
    placeholderTexte: "Coller ou rédiger ici...",
    placeholderNomMission: "Ex : Refonte site Maison Leroux",
    placeholderClientMission: "Ex : Maison Leroux (optionnel)",
    placeholderObjectifMission: "Ex : Rédiger 3 pages de vente pour la collection automne",
    contextClient: "Contexte client",
    textesBrut: "Texte brut du client",
    textesTravail: "Texte en cours",
    objetPrompt: "Objectif",
    modePrompt: "Mode",
    serviceLabel: "Service",
    serviceGhostwriting: "Ghostwriting",
    serviceRevision: "Révision",
    serviceTraduction: "Traduction",
    approcheLabel: "Approche",
    lectureLabel: "Lecture",
    reponsePrete: "Réponse prête",
    copierReponse: "Copier la réponse",
    reponseCopie: "✓ Copiée",
    revisionTitle: "Mode Révision",
    texteACorreger: "Texte à corriger",
    niveauCorrection: "Niveau de correction",
    niveauLeger: "Léger",
    niveauApprofondi: "Approfondi",
    genererCorrectionBtn: "→ Générer correction",
    texteOriginal: "Texte original",
    texteCorrigeLabel: "Texte corrigé",
    suggestionsLabel: "Suggestions",
    copierCorrection: "Copier le texte corrigé",
    correctionCopie: "✓ Copié",
    versionFinaleLabel: "Version finale",
    copierVersionFinale: "Copier la version finale",
    versionFinaleCopie: "✓ Copiée",
    tonLabel: "Ton / style",
    tonNeutre: "Neutre",
    tonProfessionnel: "Professionnel",
    tonMarketing: "Marketing",
    tonNarratif: "Narratif",
    niveauTransformationLabel: "Niveau de transformation",
    niveauTransformationSafe: "Safe",
    niveauTransformationStandard: "Standard",
    modeQualiteLabel: "Amélioration éditoriale",
    modeQualiteOff: "Désactivée",
    modeQualiteSoft: "Légère",
    livrables: "Livrables inclus",
    serviceRevisionAvancee: "Révision avancée",
    livraisonTitle: "Message de livraison",
    livraisonComplet: "Complet",
    livraisonCourt: "Court",
    copierLivraison: "Copier message client",
    livraisonCopiee: "✓ Copié",
  },
  en: {
    accueil: "← Home",
    retourMissions: "← Missions",
    voirMissions: "Missions →",
    voirAnalyser: "Analyze →",
    voirFragments: "Fragments →",
    annuler: "Cancel",
    enregistrer: "Save",
    supprimer: "Delete",
    ouvrir: "Open →",
    modifier: "Edit",
    modifierPanel: "Edit ▼",
    fermerPanel: "Close ▲",
    freelanceSubtitle: "Analyze requests · Manage missions",
    analyserDemande: "Analyze a request",
    collerMessage: "Paste the raw client message",
    messageClient: "Client message",
    placeholderMessage: "Paste the raw client message, brief, or email request here…",
    analyserBtn: "Analyze request →",
    configurerTarifs: "Configure pricing",
    typesProjet: "Project types",
    ajouterType: "+ Add type",
    coefficients: "Coefficients",
    autres: "Other",
    versionSuppl: "Additional version ($)",
    acompteConfig: "Deposit (e.g. 0.50 = 50%)",
    reinitialiser: "Reset",
    analyseInitiale: "Initial analysis",
    modificationsEnCours: "● Changes in progress",
    analyseValideeFeedback: "✓ Analysis validated",
    aucuneModification: "No changes",
    prixTotal: "Total price",
    tempsEstime: "Estimated time",
    typeBtn: "Type ↗",
    acompteLabel: "Deposit",
    creerMission: "Create mission →",
    validerAnalyse: "Validate analysis",
    analyseValideeBtn: "Analysis validated ✓",
    aConfirmer: "To confirm with client",
    infoSingulier: "item to confirm",
    infoPluriel: "items to confirm",
    informationsDetectees: "Detected information",
    informationsDeduites: "Inferred information",
    checklist: "Work checklist",
    client: "Client",
    typeDeProjet: "Project type",
    deadline: "Deadline",
    urgence: "Urgency",
    longueur: "Length",
    versions: "Versions",
    elementsClient: "Provided elements",
    complexite: "Complexity",
    mode: "Mode",
    objectif: "Goal",
    style: "Style",
    canal: "Channel",
    haute: "High ↑",
    normale: "Normal",
    basse: "Low",
    court: "Short (< 300 words)",
    moyen: "Medium (300–800 words)",
    long: "Long (800–1500 words)",
    tresLong: "Very long (> 1500 words)",
    simple: "Simple",
    standard: "Standard",
    complexe: "Complex",
    details: "Details ▼",
    reduire: "Collapse ▲",
    longueurSection: "Length",
    complexiteSection: "Complexity",
    urgenceSection: "Urgency",
    missions: "Client missions",
    nouvelleMission: "+ New mission",
    aucuneMission: "No missions yet.",
    nom: "Name",
    briefClient: "Client brief",
    modeEcriture: "Writing mode",
    creerMissionBtn: "Create mission",
    briefFourni: "Brief provided",
    textesAProduire: "Texts to produce",
    aucunTexte: "No text in this mission yet.",
    ajouterTexte: "+ Add text",
    textesSectionLabel: "Texts",
    nouveauTexte: "New text",
    titreField: "Title",
    typeField: "Type",
    texteField: "Text *",
    ajouter: "Add",
    brutClient: "Raw client",
    enTravail: "Working draft",
    copierIA: "Copy for AI",
    genererPrompt: "Generate prompt →",
    copie: "✓ Copied",
    missionIntrouvable: "Mission not found.",
    statutAFaire: "to do",
    statutEnCours: "in progress",
    statutTermine: "done",
    placeholderClient: "Client name",
    placeholderDeadline: "Ex: May 15, Friday, within 3 days",
    placeholderObjectif: "Main project goal",
    placeholderStyle: "Ex: clean / elegant, dynamic / punchy",
    placeholderTitre: "Ex: Home page (optional)",
    placeholderTexte: "Paste or write here...",
    placeholderNomMission: "Ex: Maison Leroux Website Redesign",
    placeholderClientMission: "Ex: Maison Leroux (optional)",
    placeholderObjectifMission: "Ex: Write 3 sales pages for the autumn collection",
    contextClient: "Client context",
    textesBrut: "Raw client text",
    textesTravail: "Working draft",
    objetPrompt: "Goal",
    modePrompt: "Mode",
    serviceLabel: "Service",
    serviceGhostwriting: "Ghostwriting",
    serviceRevision: "Revision",
    serviceTraduction: "Translation",
    approcheLabel: "Approach",
    lectureLabel: "Overview",
    reponsePrete: "Ready-to-send response",
    copierReponse: "Copy response",
    reponseCopie: "✓ Copied",
    revisionTitle: "Revision mode",
    texteACorreger: "Text to correct",
    niveauCorrection: "Correction level",
    niveauLeger: "Light",
    niveauApprofondi: "In-depth",
    genererCorrectionBtn: "→ Generate correction",
    texteOriginal: "Original text",
    texteCorrigeLabel: "Corrected text",
    suggestionsLabel: "Suggestions",
    copierCorrection: "Copy corrected text",
    correctionCopie: "✓ Copied",
    versionFinaleLabel: "Final version",
    copierVersionFinale: "Copy final version",
    versionFinaleCopie: "✓ Copied",
    tonLabel: "Tone / style",
    tonNeutre: "Neutral",
    tonProfessionnel: "Professional",
    tonMarketing: "Marketing",
    tonNarratif: "Narrative",
    niveauTransformationLabel: "Transformation level",
    niveauTransformationSafe: "Safe",
    niveauTransformationStandard: "Standard",
    modeQualiteLabel: "Editorial improvement",
    modeQualiteOff: "Off",
    modeQualiteSoft: "Light",
    livrables: "Deliverables included",
    serviceRevisionAvancee: "Advanced revision",
    livraisonTitle: "Delivery message",
    livraisonComplet: "Full",
    livraisonCourt: "Short",
    copierLivraison: "Copy client message",
    livraisonCopiee: "✓ Copied",
  },
} as const;

export function chargerLang(): Lang {
  try { return (localStorage.getItem("freelance-lang") as Lang) || "fr"; }
  catch { return "fr"; }
}

export function sauvegarderLang(lang: Lang): void {
  try { localStorage.setItem("freelance-lang", lang); }
  catch { /* ignore */ }
}

export function afficherStatut(statut: string, lang: Lang): string {
  if (lang === "fr") return statut;
  const map: Record<string, string> = {
    "à faire":  "to do",
    "en cours": "in progress",
    "terminé":  "done",
  };
  return map[statut] ?? statut;
}
